### ISSUE TITLE
csv_a_tf.py --csv_input=CSV/entrenamiento.csv error

### ISSUE THREAD

**Issue by Torras86** [puigalex/deteccion_objetos#2]
Hi there,
When i execute the command 
`"sudo python3 csv_a_tf.py --csv_input=CSV/entrenamiento.csv --output_path=TFRecords/entrenamiento.record --images=images" `
it gives me the following error:

Traceback (most recent call last):
  File "csv_a_tf.py", line 102, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "csv_a_tf.py", line 93, in main
    tf_example = create_tf_example(group, path)
  File "csv_a_tf.py", line 68, in create_tf_example
    classes.append(class_text_to_int(row['class']))
  File "csv_a_tf.py", line 34, in class_text_to_int
    identifier = label_map_dict[row_label]
KeyError: '.3'

Can you help me with what is happening please?
I'm using Debian 10
Regards

Por cierto, puedes responderme en español

**Comment by Torras86** [comment]
I found what was causing the error:
One of the images had a wrong named label
